

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaik
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    static Socket s;
    static ServerSocket ss;
    static InputStreamReader isr;
    static BufferedReader br;
    static String message;
    static String Compname;
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setAutoRequestFocus(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApplogo.jpeg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 210, 160));

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel1.setText("PC Remote Monitoring");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 570, 59));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText(" By Arbaj Momin ,Khalid Shaikh ,Rehan Lukade ,Habiballa Attar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 642, 24));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel3.setText(" PC Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 460, 57));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText(" Please Make Connection With The mobile to Experience this Applicaton !!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 440, 1190, 53));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsAppyellowback.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.awt.AWTException
     */
    public static void main(String args[]) throws AWTException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
            
            jLabel3.setFont(new java.awt.Font("Bell MT", 1, 36));
            jLabel3.setForeground(Color.BLACK);
            jLabel3.setText(" PC Name : "+Compname);
        });
        try{
             java.net.InetAddress comname= java.net.InetAddress.getLocalHost();
              Compname=comname.getHostName();
           // System.out.println(comname.getHostName());
            // Compname=comname.getHostName();
              
           
            //  System.out.println(Compname);
            ss=new ServerSocket(7800);
    
            while(true)
            {
                s=ss.accept();
                isr=new InputStreamReader(s.getInputStream());
                br=new BufferedReader(isr);
                message=br.readLine();
                String ipadr=(((InetSocketAddress)s.getRemoteSocketAddress()).getAddress()).toString().replace("/","");
                 //activity 2 code start here
                
                switch (message) {
                    case "Stop":
                        jLabel6.setIcon(new javax.swing.ImageIcon(NewJFrame.class.getResource(("/WhatsAppyellowback.jpeg"))));
                        jLabel6.setText("");
                        jLabel4.setText(" Please Make Connection With The mobile to Experience this Applicaton !!");
                        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 24));
                        jLabel4.setForeground(Color.RED);
                        s.close();
                        break;
                //ends here
                    case "Screenshot":
                     //   System.out.println(message);
                        Robot r = new Robot();
                        // It saves screenshot to desired path
                        String path = "C:// Shot.jpg";
                        // Used to get ScreenSize and capture image
                        Rectangle capture =
                        new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
                        BufferedImage Image = r.createScreenCapture(capture);
                        ImageIO.write(Image, "jpg", new File(path));
                        //System.out.println("Screenshot saved");
                        s = new Socket (ipadr,7800);
                        OutputStream os= s.getOutputStream();
                        DataOutputStream dos = new DataOutputStream(os);
                        File input_file =new File(path);
                        BufferedImage image = ImageIO.read(input_file);
                        ByteArrayOutputStream baos= new ByteArrayOutputStream();
                        ImageIO.write(image, "jpg", baos);
                        byte[] array = baos.toByteArray();
                        //os.write(baos.toByteArray());
                        dos.writeInt(array.length);
                        dos.write(array,0,array.length);
                        dos.close();
                        os.flush();
                        os.close();
                        s.close();
                        //System.out.println("Screenshot send");
                        // JOptionPane.showMessageDialog(null, "sent");
                        break;
                    default:
                       // System.out.println(message);
                        jLabel6.setIcon(new javax.swing.ImageIcon(NewJFrame.class.getResource(("/3175.jpg"))));
                        jLabel6.setText("");
                       // jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 730));
                        jLabel4.setText(" Connected User :  "+message);
                        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 36));
                        jLabel4.setForeground(Color.BLACK);
                        
                        s.close();
                        break;            
                }
                
            }    
            
        }catch(IOException e)
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
